# Generated by Django 5.1.6 on 2025-02-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.ManyToManyField(null=True, to='api.authormodel'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
